---
- name: install docker
  yum: name=docker state=latest

- name: service docker
  service:
    name=docker
    state=started
    enabled=yes

- name: enable docker for dev user
  user: name={{ developer_name }} group=docker append=yes